#!/bin/bash

BKU=Fedora-Setup_$(date +%Y-%m-%d).tgz

# If there's a fedora-post-install directory, tarball it
if [ -d ~/Projects/fedora-post-install/ ]; then
	cd ~/Projects/
	tar -czvf "$BKU" fedora-post-install
	echo "Successfully created archive!"
else
	echo "ERROR : Could not find directory to be archived"
fi
