#!/bin/bash

# batch exif data scrubber for all images

recursive=$1

IFS=$(echo -en "\n\b")

# recursive limited to 3 levels
if [[ $recursive = "-r" ]]; then
  recursive=3
else
  recursive=0
fi

images=$(find * -maxdepth $recursive -type f -exec file --mime-type '{}' \; \
| awk -F: '{if ($2 ~/image\//) print $1}')


for i in $images; do
	echo "Cleaning.." "$i"
	exiftool -a -all= -overwrite_original "$i"
	echo
done

