#!/usr/bin/env bash


ZIPPY=Fedora-Setup_$(date +%Y-%m-%d).tgz


# if there's a 'fedora-setup' directory, tarball it
if [[ -d ~/Projects/fedora-setup/ ]]; then
    ( 
      cd ~/Projects/;
      tar -czvf "$ZIPPY" fedora-setup 
    )
    echo "Successfully created archive!"
  else
    echo "ERROR : Could not find directory to be archived"
fi

