#!/usr/bin/env bash

# check connection, enable VPN if good

RUN="1 minute"
END=$(date -ud "$RUN" +%s)

while [[ $(date -u +%s) -le $END ]]; do
  ping -c 3 1.1.1.1 &> /dev/null
  if [[ $? = 0 ]]; then
	  nordvpn c
	  break
  else
	  continue
  fi
done
